### ISSUE TITLE
dlink-qiling exited with code 0

### ISSUE THREAD

**Issue by theoyuandawang** [firmianay/IoT-vulhub#4]
在Dlink文件下的sudo docker-compose -f docker-compose-qiling.yml up 
出现了“dlink-qiling exited with code 0”的问题
请问qiling这个模拟环境是否需要添加其他的额外依赖呢？

**Comment by firmianay** [comment]
看了眼这个环境好像缺东西。。。可能是换电脑时候搞丢了，我有空补上。。。师傅搞定了也可以PR，谢谢！

Theoyuandawang <notifications@github.com> 于2021年1月8日周五 上午1:54写道：

**Comment by theoyuandawang** [comment]
好的师傅，我尝试下，谢谢师傅

**Comment by harry1080** [comment]
我也出现这个问题Attaching to dlink-firmadyne
dlink-firmadyne  |  * Starting PostgreSQL 9.3 database server
dlink-firmadyne  |    ...done.
dlink-firmadyne exited with code 0
请问大佬有解决方案
